---
- name: Add nodes to hadoop-cluster group
  add_host:
    name: "{{ hostvars[local_loop]['inventory_hostname'] }}"
    ansible_host: "{{ hostvars[local_loop]['ansible_host']|default(hostvars[local_loop]['inventory_hostname']) }}"    
    ansible_user: "{{ hostvars[local_loop]['ansible_user']|default('root') }}"
    ansible_ssh_private_key_file: "{{ hostvars[local_loop]['ansible_ssh_private_key_file']|default(omit) }}"
    ansible_ssh_pass: "{{ hostvars[local_loop]['ansible_ssh_pass']|default(omit) }}"
    ansible_become_user: root
    groups: hadoop-cluster
  loop_control:
    loop_var: local_loop
  with_items: "{{ groups['all'] }}"
  when: groups['hadoop-cluster'] is not defined or groups['hadoop-cluster']|length == 0

